import os
from dotenv import load_dotenv
load_dotenv()

SECRET_KEY = os.getenv("SECRET_KEY")

MONGO_URI = os.getenv("MONGO_URI")

CACHE_TYPE = os.getenv("CACHE_TYPE")
CACHE_DEFAULT_TIMEOUT = os.getenv("CACHE_DEFAULT_TIMEOUT")

SERVER_SOCKET_HOST = os.getenv("SERVER_SOCKET_HOST")
SERVER_SOCKET_PORT = int(os.getenv("SERVER_SOCKET_PORT"))

JWT_TOKEN_LOCATION = "headers"
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
JWT_ACCESS_TOKEN_EXPIRES = 1800
JWT_REFRESH_TOKEN_EXPIRES = 17280000000