import os
from dotenv import load_dotenv
load_dotenv()

SECRET_KEY = os.getenv("SECRET_KEY")

MONGO_URI = os.getenv("MONGO_URI")

SERVER_SOCKET_HOST = os.getenv("SERVER_SOCKET_HOST")
SERVER_SOCKET_PORT = int(os.getenv("SERVER_SOCKET_PORT"))

JWT_TOKEN_LOCATION = ["cookies"]
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
JWT_COOKIE_CSRF_PROTECT = False
JWT_COOKIE_HTTPONLY = True 
JWT_CSRF_IN_COOKIES = False
JWT_COOKIE_SECURE = True
JWT_COOKIE_SAMESITE = "Lax"
JWT_ACCESS_TOKEN_EXPIRES = 1800
JWT_REFRESH_TOKEN_EXPIRES = 2592000

CORS_SUPPORTS_CREDENTIALS = True